spring:
  application:
    name: robert-ui

  threads:
    virtual:
      enabled: true

management:
  info:
    build:
      enabled: true
    git:
      mode: FULL
    java:
      enabled: true
    os:
      enabled: true
  endpoint:
    health:
      show-details: ALWAYS
    metrics:
      enabled: true
    prometheus:
      enabled: true
    env:
      enabled: true
      show-values: ALWAYS
    configprops:
      enabled: true
      show-values: ALWAYS
  endpoints:
    web:
      exposure:
        include: info,health,metrics,scheduledtasks,loggers,prometheus,sbom
  tracing:
    sampling:
      probability: 1.0

refactor:
  service:
    scheme: ${REFACTOR_SERVICE_SCHEME:http}
    host: ${REFACTOR_SERVICE_HOST:localhost}
    port: ${REFACTOR_SERVICE_PORT:8080}
    url: ${refactor.service.scheme}://${refactor.service.host}:${refactor.service.port}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

vaadin:
  launch-browser: true
  allowed-packages: com.vaadin,org.vaadin

---

spring:
  config:
    activate:
      on-profile: local

server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: dev

debug: true

management:
  endpoints:
    web:
      exposure:
        include: "*"